<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('team')->insert([
            'name' => 'Jennifer Linda',
            'age' => '25',
            'job' => 'Product Designer',
            'profile_img' => 'img/team/jenifer.png',
            'link_linkedin' => 'https://www.linkedin.com/login/in',
            'link_instagram' => 'https://www.instagram.com/',
            'link_twitter' => 'https://twitter.com/i/flow/login',
            'email' => 'serana@email.com',
            'box_message_heading' => 'Platform helped me to increase my sales and revenue generated by bluebase technologies',
            'box_message_desc' => "One aspect that IT Services apart is their proactive approach to security. In today's digital landscape, protecting our sensitive data is of utmost importance",
            'button_link' => 'https://wpriverthemes.com/HTML/synck/index.html',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
    }
}
